project:
  type: website

website:

  search:
    location: sidebar
    type: overlay
  navbar:
    background: "#0A4393"
    height: 55
    foreground: "light"
    logo: "_images/logos/combinedLogo.svg"
    pinned: true
    
    
  title: "COPERNICUS DATA SPACE ECOSYSTEM DOCUMENTATION PORTAL"
  

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - section: "Introduction"
        contents:
          - Home.md
      - section: "Service description and evolution roadmap"
        contents:
          - ServiceDescriptionRoadmap.md
      - section: "Roadmap"
        contents:
          - Roadmap.md
          - Roadmap/DataTable.html
      - section: "User registration and authentication"
        contents: 
        - Registration.md


format:
  html:
    theme: 
    - cosmo
    - custom.scss
    toc: false
