project:
  type: website

website:

  search:
    location: sidebar
    type: overlay
  navbar:
    background: "#0A4393"
    height: 55
    foreground: "light"
    logo: "_images/logos/combinedLogo.svg"
    pinned: true
    
  page-navigation: true
    
    
  title: "COPERNICUS DATA SPACE ECOSYSTEM DOCUMENTATION PORTAL"
  

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - href: Home.md
        text: Welcome
      - section: "Service description and evolution roadmap"
        href: Roadmap.md
        contents: 
          - href: Roadmap/DataTable.qmd
          - href: Roadmap/APITable.qmd
          - href: Roadmap/AppTable.qmd
      - href: Registration.md
        text: User registration and authentication
      - section: "Data"
        href: Data.md
        contents: 
          - href: Data/Sentinel1.md
          - href: Data/Sentinel2.md
          - href: Data/Sentinel3.md
          - href: Data/Sentinel5P.md
      - section: "APIs"
        href: APIs.md
        contents: 
          - href: APIs/OData.md
          - href: APIs/OpenSearch.md
          - section: "Sentinel Hub"
            href: "APIs/SentinelHub.md"
            contents:
              - section: "API Overview"
                href: "APIs/SentinelHub/Overview.md"
                contents:
                  - href: "APIs/SentinelHub/Overview/Authentication.md"
              - section: "Catalog API"
                href: "APIs/SentinelHub/Catalog.md"
                contents:
                  - href: "APIs/SentinelHub/Catalog/Examples.md"
      - section: "Applications"
        href: Applications.md
        contents: 
          - href: Applications/Browser.md
      - href: FAQ.md
        text: FAQ
      - href: Support.md
        text: Support
    


format:
  html:
    toc: true
    toc-depth: 4
    css: custom.scss
