project:
  type: website

website:
  title: "Copernicus Dataspace Ecosystem Docs"
  navbar:
    logo: https://documentation.dataspace.copernicus.eu/_images/logos/copernicus-white-BL.svg
    left:
      - href: Home.md
        text: Home
      - Roadmap.md
      - Applications.md
      - Data.md
      - APIs.md
      - FAQ.md
      - Support.md
      - openeo.qmd

format:
  html:
    theme: cosmo
    toc: true
