project:
  type: website

website:

  navbar:
    background: "#0A4393"
    foreground: "light"
    logo: "_images/logos/combinedLogo.svg"
    pinned: true
    search: false
    
    right:
      - text: "COPERNICUS DATA SPACE ECOSYSTEM DOCUMENTATION PORTAL"
  

  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Introduction"
        contents:
          - Home.md
      - section: "Service description and evolution roadmap"
        contents:
          - ServiceDescriptionRoadmap.md
      - section: "Roadmap"
        contents:
          - Roadmap.md
          - Roadmap/DataTable.html
      - section: "User registration and authentication"
        contents: 
        - Registration.md



format:
  html:
    theme: cosmo
    toc: false
