name: Merge PR branch into preview
on: 
  pull_request:
    branches: [quartov2]
    types: [opened, edited, synchronize]
jobs:
  merge-PR-to-preview:
    timeout-minutes: 2
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v2    
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"    
    - name: Merge main back to preview
      run: |
          git fetch --unshallow
          git checkout preview
          git pull
          echo ${GITHUB_REF##*/}
          echo ${GITHUB_REF_NAME}
          git merge --no-ff ${GITHUB_REF_NAME} -m "Auto-merge ${GITHUB_REF_NAME} to preview"
          git push
